-- Alte Tabellen Löschen
DROP TABLE Besteller CASCADE CONSTRAINTS;
DROP TABLE Bestellung CASCADE CONSTRAINTS;
DROP TABLE Anruf CASCADE CONSTRAINTS;

-- Neue Tabellen Erstellen
CREATE TABLE Besteller(
TELEFON NUMBER(5,0),
NAME VARCHAR(10),
ORT VARCHAR(10)
);

CREATE TABLE Bestellung(
ANUMMER NUMBER(1,0),
PNUMMER NUMBER(1,0),
MENGE NUMBER(5,0)
);

CREATE TABLE Anruf(
    NUMMER NUMBER(1,0),
    TELEFON NUMBER(5,0),
    DATUM VARCHAR(10),
    UHRZEIT VARCHAR(5)
);

CREATE TABLE Pizza(
    NUMMER NUMBER(1,0),
    NAME VARCHAR(10),
    PREIS NUMBER(2,1)
);